# Generated by Django 3.0.8 on 2020-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0002_auto_20200802_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
