# Generated by Django 3.0.8 on 2020-08-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0003_auto_20200802_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
