# Generated by Django 3.0.8 on 2020-08-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0006_auto_20200805_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
