# Generated by Django 3.1 on 2020-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0010_dictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='true_quantity',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
