# Generated by Django 3.1 on 2020-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0012_entry_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
