# Generated by Django 3.1 on 2020-08-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0013_auto_20200825_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='entry',
        ),
    ]
