# Generated by Django 3.1 on 2020-08-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0014_auto_20200827_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
